inbound:
  boxes:
  - {name: "robot_box",       frame: "robot_bottles_link",       position: [ 0.05, 0.1, 0.35], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, -0.1], leave_distance: [0, 0, -0.1] }
  # - {name: "human_box",       frame: "user_bottles_link",        position: [ 0.05, 0.1, 0.35], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, -0.1], leave_distance: [0, 0, -0.1] }
  - {name: "both_agents_box", frame: "both_agents_bottles_link", position: [ 0.05, 0.1, 0.35], quaternion: [1, 0, 0, 0], approach_distance: [0, 0, -0.1], leave_distance: [0, 0, -0.1] }
