inbound:
  objects:
  # - {type: "AAA", frame: "table", position: [0.175, 0.870, 0.22], quaternion: [0.708, -0.706, -0.004, -0.002], inbound: "AAA_box"}
  # - {type: "AAA", frame: "table", position: [0.175, 0.91, 0.22], quaternion: [0.708, -0.706, -0.004, -0.002], inbound: "AAA_box"}
  # - {type: "AAA", frame: "table", position: [0.175, 0.95, 0.22], quaternion: [0.708, -0.706, -0.004, -0.002], inbound: "AAA_box"}
  # - {type: "AAA", frame: "table", position: [0.175, 0.99, 0.22], quaternion: [0.708, -0.706, -0.004, -0.002], inbound: "AAA_box"}
  # - {type: "AAA", frame: "table", position: [0.175, 1.03, 0.22], quaternion: [0.708, -0.706, -0.004, -0.002], inbound: "AAA_box"}
  # - {type: "AAA", frame: "table", position: [0.175, 1.07, 0.22], quaternion: [0.708, -0.706, -0.004, -0.002], inbound: "AAA_box"}
  - {type: "AAA", frame: "table", position: [0.175, 0.870, 0.220], quaternion: [1.000, 0.001, -0.001, -0.004], inbound: "AAA_box"}
  - {type: "AAA", frame: "table", position: [0.175, 0.91, 0.220], quaternion: [1.000, 0.001, -0.001, -0.004], inbound: "AAA_box"}
  - {type: "AAA", frame: "table", position: [0.175, 0.95, 0.220], quaternion: [1.000, 0.001, -0.001, -0.004], inbound: "AAA_box"}
  - {type: "AAA", frame: "table", position: [0.175, 0.99, 0.220], quaternion: [1.000, 0.001, -0.001, -0.004], inbound: "AAA_box"}
  - {type: "AAA", frame: "table", position: [0.175, 1.03, 0.220], quaternion: [1.000, 0.001, -0.001, -0.004], inbound: "AAA_box"}
  - {type: "AAA", frame: "table", position: [0.175, 1.07, 0.220], quaternion: [1.000, 0.001, -0.001, -0.004], inbound: "AAA_box"}

  # - {type: "robot_bottle",  frame: "robot_bottles_link",        position: [0.2, 0.05, 0.1],  quaternion: [0, 0, 0, 1], inbound: "robot_box"}
  # - {type: "robot_bottle",  frame: "robot_bottles_link",        position: [0.3, 0.05, 0.1],  quaternion: [0, 0, 0, 1], inbound: "robot_box"}
  # - {type: "robot_bottle",  frame: "robot_bottles_link",        position: [0.1, 0.15, 0.1],  quaternion: [0, 0, 0, 1], inbound: "robot_box"}
  # - {type: "robot_bottle",  frame: "robot_bottles_link",        position: [0.2, 0.15, 0.1],  quaternion: [0, 0, 0, 1], inbound: "robot_box"}
  # - {type: "robot_bottle",  frame: "robot_bottles_link",        position: [0.3, 0.15, 0.1],  quaternion: [0, 0, 0, 1], inbound: "robot_box"}
  #
  # # - {type: "user_bottle", frame: "user_bottles_link",        position: [0, 0, 0], quaternion: [0, 0, 0, 1], inbound: "human_box"}
  # # - {type: "user_bottle", frame: "user_bottles_link",        position: [0, 0.1, 0], quaternion: [0, 0, 0, 1], inbound: "human_box"}
  # # - {type: "user_bottle", frame: "user_bottles_link",        position: [0, 0.2, 0], quaternion: [0, 0, 0, 1], inbound: "human_box"}
  # # - {type: "user_bottle", frame: "user_bottles_link",        position: [0.1, 0, 0], quaternion: [0, 0, 0, 1], inbound: "human_box"}
  # # - {type: "user_bottle", frame: "user_bottles_link",        position: [0.1, 0.1, 0], quaternion: [0, 0, 0, 1], inbound: "human_box"}
  # # - {type: "user_bottle", frame: "user_bottles_link",        position: [0.1, 0.2, 0], quaternion: [0, 0, 0, 1], inbound: "human_box"}
  #
  # - {type: "both_agents_bottle",   frame: "both_agents_bottles_link", position: [0.1, 0.05, 0.05],  quaternion: [0, 0, 0, 1], inbound: "both_agents_box"}
  # - {type: "both_agents_bottle",   frame: "both_agents_bottles_link", position: [0.2, 0.05, 0.05],  quaternion: [0, 0, 0, 1], inbound: "both_agents_box"}
  # - {type: "both_agents_bottle",   frame: "both_agents_bottles_link", position: [0.1, 0.15, 0.05],  quaternion: [0, 0, 0, 1], inbound: "both_agents_box"}
  # - {type: "both_agents_bottle",   frame: "both_agents_bottles_link", position: [0.2, 0.15, 0.05],  quaternion: [0, 0, 0, 1], inbound: "both_agents_box"}
  # - {type: "both_agents_bottle",   frame: "both_agents_bottles_link", position: [0.1, 0.25, 0.05],  quaternion: [0, 0, 0, 1], inbound: "both_agents_box"}
  # - {type: "both_agents_bottle",   frame: "both_agents_bottles_link", position: [0.2, 0.25, 0.05],  quaternion: [0, 0, 0, 1], inbound: "both_agents_box"}
