group_name: "manipulator"
recipe:
- {action: "goto",   description: ["localization"],  property_exec_id: "board_localization",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}

message: "Loading"
position: 2
storage: 0
